emu_config:
   work_dir_client: ~/work
   engines: 1
   target_nodes: 
   - 1
   design_name: SFU1_1_SBTR
   fpga_engine_module: ./benchmarks/HyperFPGA/4_SFU1/hyperfpga/fpga_engine.py
   load_args:
      work_dir: ./
   write_args:
      work_dir: ./
      mode: golden
   max_num_faults: 1
   sim_runtime: 10000
   tasks: 2
   src_data_root_dir: ./benchmarks/Cores/SFU/SFU_1/tb
   test_data_info:
     test_app_dirs: 
      - ./SFU_input_data
     test_app_files: 
   fpga_hw:
     vivado_proj_dir: ./benchmarks/HyperFPGA/4_SFU1/vivado/1_SBTR/hyperfpga-basic-test-3be11
  
    
  