shadowfi_root:
project:
  name: 
  root_proj_dir: 
  bench_name: #<optional list>
  work_dir: 
  proj_config_file:
  design_config:
    design_root_dir:
    inc_directories: #<optional list>
    src_path: 
    src_list_files: #<optional list>
    top_module: 
    module_params: #<optional list>   
  testbench_config:
    external_tb_build: False
    external_tb_config: 
      tb_build_cmd:  #<optional list>
      tb_working_dir: 
    internal_tb_config: 
       tb_list_files:
       tb_path: 
       tb_working_dir: 
       tb_target_file: 
       tb_top: 
       tb_inc_directories:  #<optional list>
       tb_params: #<optional list>
       tb_verilator_params: #<optional> 
  sim_config:
    tasks: 1
    engines: 1
    sim_runtime: 
    max_num_faults: 1
    work_sim_root_dir: 
    work_sim_dir: 
    tb_build_dir: 
    tb_run_info:
      tb_run_script: 
      tb_run_args: #<optional str>
      tb_run_timeout: #<optional>
      tb_run_env_vars: #<optional list>
    tb_sdc_check_info:
      tb_sdc_check_script: 
      tb_sdc_check_args: #<optional>
      tb_sdc_check_env_vars: #<optional list>
    tb_test_app_info:
      test_app: #<optional>
      test_app_args: #<optional>
      test_app_env_vars: #<optional list>
      test_app_dirs: #<list rel dirs>
      test_app_files: #<list rel files>
    slurm:
      account: 
      partition: 
      qos: 
      time: 
      nodes: 
      tasks_per_node: 
      cpus_per_task: 
      mem: 
      job_name: 
      output: 
      error: 
  sbtr_config:
    sbtr_dir:
    component_selection:
      mode:
      hierarchical_component:
      target_modules: 
    fault_model: S@
    max_num_faults: -1


    




# "design_info": {
#         "inc_directories": [],
#         "src_list_files": [],
#         "module_params": []},
#     "testbench_info": {
#         "make_sim_tb": False,
#         "inc_directories": [],
#         "tb_list_files": [],
#         "tb_target_file": "",
#         "tb_top": "",
#         "tb_params": [],
#         "verilator_params": "--trace --trace-depth 1",
#         "make_cmd": ""},
#     "target_modules": [],
#     "hierarchical_component": [], 