sim_config:
  jobs: 1
  workers: 1
  sim_runtime: 10000
  max_num_faults: 1
  work_sim_root_dir: /home/juancho/Documents/GitHub/EmuFaultSim/shadowfi/benchmarks/Cores/TCU/TCU_2/tb
  work_sim_dir: ./
  tb_build_dir: ./obj_dir
  tb_run_info:
    tb_run_script: ./run.sh
    tb_run_args: ''
    tb_run_timeout: 1000
    tb_run_env_vars: 
  tb_sdc_check_info:
    tb_sdc_check_script: ./sdc_check.sh
    tb_sdc_check_args: ''
    tb_sdc_check_env_vars: 
  tb_test_app_info:
    test_app: test_app
    test_app_args: ''
    test_app_env_vars: 
    test_app_dirs: 
    test_app_files: 
      - ./values_dot_product.csv
  slurm:
    account: emufaultsim
    partition: emufaultsim
    qos: emufaultsim
    time: 00:10:00
    nodes: 1
    tasks_per_node: 1
    cpus_per_task: 1
    mem: 4G
    job_name: TCU_sim
    output: /home/juancho/Documents/GitHub/EmuFaultSim/shadowfi/projects/TCU/work/logs/slurm-%j.out
    error: /home/juancho/Documents/GitHub/EmuFaultSim/shadowfi/projects/TCU/work/logs/slurm-%j.err
  
    
  