component_selection:
  hierarchical_component:
  - d_unit0@adder0->fpadd_3_pipe_sbtr

  # - d_unit0@adder0->fpadd_3_pipe_sbtr
  # - d_unit1@adder1->fpadd_3_pipe_sbtr

  # - d_unit0@adder0->fpadd_3_pipe_sbtr
  # - d_unit1@adder0->fpadd_3_pipe_sbtr
  # - d_unit2@adder0->fpadd_3_pipe_sbtr
  # - d_unit3@adder0->fpadd_3_pipe_sbtr

  # - d_unit0@adder0->fpadd_3_pipe_sbtr
  # - d_unit1@adder0->fpadd_3_pipe_sbtr
  # - d_unit2@adder0->fpadd_3_pipe_sbtr
  # - d_unit3@adder0->fpadd_3_pipe_sbtr
  # - d_unit4@adder0->fpadd_3_pipe_sbtr
  # - d_unit5@adder0->fpadd_3_pipe_sbtr
  # - d_unit6@adder0->fpadd_3_pipe_sbtr
  # - d_unit7@adder0->fpadd_3_pipe_sbtr


  # - d_unit0@adder0->fpadd_3_pipe_sbtr
  # - d_unit1@adder0->fpadd_3_pipe_sbtr
  # - d_unit2@adder0->fpadd_3_pipe_sbtr
  # - d_unit3@adder0->fpadd_3_pipe_sbtr
  # - d_unit4@adder0->fpadd_3_pipe_sbtr
  # - d_unit5@adder0->fpadd_3_pipe_sbtr
  # - d_unit6@adder0->fpadd_3_pipe_sbtr
  # - d_unit7@adder0->fpadd_3_pipe_sbtr
  # - d_unit8@adder0->fpadd_3_pipe_sbtr
  # - d_unit9@adder0->fpadd_3_pipe_sbtr
  # - d_unit10@adder0->fpadd_3_pipe_sbtr
  # - d_unit11@adder0->fpadd_3_pipe_sbtr
  # - d_unit12@adder0->fpadd_3_pipe_sbtr
  # - d_unit13@adder0->fpadd_3_pipe_sbtr
  # - d_unit14@adder0->fpadd_3_pipe_sbtr
  # - d_unit15@adder0->fpadd_3_pipe_sbtr
  target_modules:
  - fpadd_3_pipe


# component_selection:
#   hierarchical_component:
#   - d_unit6@adder1@roundingadder->intadder_31_freq150_uid13_sbtr
#   - d_unit5@fmul3@flopocofpmult@significandmultiplication@tile_1_mult->dspblock_7x24_freq625_uid11_sbtr
#   - d_unit10@fmul2@inputy->inputieee_sbtr
#   - d_unit15@fmul3@flopocofpmult@roundingadder->intadder_33_freq625_uid17_sbtr
#   - d_unit9@fmul0@outputr->outputieee_sbtr
#   - d_unit9@fmul3@inputy->inputieee_sbtr
#   - d_unit0@fmul2@inputy->inputieee_sbtr
#   - d_unit1@fmul2@inputy->inputieee_sbtr
#   - d_unit4@adder2@ieeefpadd_8_23_freq150_uid2leadingzerocounter->lzc_26_freq150_uid8_sbtr
#   target_modules:
#   - intadder_31_freq150_uid13
#   - dspblock_7x24_freq625_uid11
#   - inputieee
#   - intadder_33_freq625_uid17
#   - outputieee
#   - lzc_26_freq150_uid8