model:
  name: vgg11
  num_classes: 10

dataset:
  name: mnist
  normalize: True
  max_test_samples: 100

training:
  batch_size_train: 100
  batch_size_test: 10
  num_workers_train: 4
  num_workers_test: 0
  pin_memory: false
  persistent_workers: false

paths:
  dataset_root: datasets
  model_fp32: pytorch/models/vgg/pretrained/vgg11_fp32.pth
  model_int8: pytorch/models/vgg/pretrained/vgg11_int8.pth
  output_dir: pytorch/models/vgg/pretrained/profiles

logging:
  level: INFO
  log_file: logs/vgg.log

backend:
  name: tensor
  bitwidth: 8
  format: "float"
  backend_layers: ["conv2d"]
